services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sampledb
    ports:
      - "43544:5432"
    volumes:
      - postgres_data:/home/nabutabu/programs/crane-oss/postgres_data

  localstack:
    image: localstack/localstack:latest
    container_name: crane-localstack
    ports:
      - "4566:4566"  # LocalStack edge service
      - "4510-4559:4510-4559"  # Service port range
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dominator:
    build:
      context: .
      dockerfile: Dockerfile.dominator
    container_name: crane-dominator
    ports:
      - "44000:44000"
    # depends_on:
    #   db:
    #     condition: service_started
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=crane
      - SPIFFE_ENDPOINT_SOCKET=unix:///tmp/spire-agent/public/api.sock
    volumes:
      - ./policy:/app/policy
      - spire_agent_socket:/tmp/spire-agent/public


  crane-api:
    build:
      context: .
      dockerfile: Dockerfile.crane-api
    container_name: crane-api
    ports:
      - "43060:43060"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=crane
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - db
      - localstack

  spire-server:
    image: ghcr.io/spiffe/spire-server:1.9.3
    container_name: crane-spire-server
    command: ["-config", "/opt/spire/conf/server/server.conf"]
    ports:
      - "8081:8081"
    volumes:
      - ./spire/server:/opt/spire/conf/server
      - ./spire/server/data:/opt/spire/data
    depends_on:
      - db

  spire-agent:
    image: ghcr.io/spiffe/spire-agent:1.9.3
    container_name: crane-spire-agent
    entrypoint: ["/opt/spire/bin/spire-agent"]
    pid: host
    command: ["run", "-config", "/opt/spire/conf/agent/agent.conf", "-joinToken", "<join_token>"]
    depends_on:
      - spire-server
    volumes:
      - ./spire/agent:/opt/spire/conf/agent
      - ./spire/agent/data:/opt/spire/data
      - spire_agent_socket:/tmp/spire-agent/public      

volumes:
  postgres_data:
  spire_agent_socket: