services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sampledb
    ports:
      - "43544:5432"
    volumes:
      - postgres_data:/home/nabutabu/programs/crane-oss/postgres_data

  localstack:
    image: localstack/localstack:latest
    container_name: crane-localstack
    ports:
      - "4566:4566"  # LocalStack edge service
      - "4510-4559:4510-4559"  # Service port range
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
