FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /crane-api ./cmd/crane-api

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /crane-api .
COPY --from=builder /app/internal/provider/awscompute/cloud-init.yaml ./
COPY bhd.json ./

EXPOSE 43060

ENTRYPOINT ["./crane-api"]
