server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    trust_domain = "crane.internal"
    data_dir = "/opt/spire/data"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "postgres"
            connection_string = "host=db port=5432 dbname=spire user=postgres password=mysecretpassword sslmode=disable"
        }
    }

    NodeAttestor "aws_iid" {
        plugin_data {
            account_id_whitelist = ["AKIA5JBCYANFBNA6VFE7"]
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            keys_path = "/opt/spire/data/keys"
        }
    }
}
