agent {
    data_dir = "/opt/spire"
    trust_domain = "crane.internal"
    server_address = "<SPIRE_SERVER_IP>"
    server_port = "8081"
    socket_path = "/tmp/spire-agent/public/api.sock"
}

NodeAttestor "aws_iid" {
    plugin_data {}
}