agent {
    data_dir = "/opt/spire"
    trust_domain = "crane.internal"
    server_address = "<SPIRE_SERVER_IP>"
    server_port = "8081"
    socket_path = "/tmp/spire-agent/public/api.sock"
}

plugins {
    WorkloadAttestor "unix" {
        plugin_data {}
    }

    NodeAttestor "aws_iid" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/opt/spire/data"
        }
    }
}